# Generated by Django 6.0.5 on 2026-05-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardedadevent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="rewardedadevent",
            name="provider",
            field=models.CharField(default="mock", max_length=50),
        ),
        migrations.AlterField(
            model_name="rewardedadevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("duplicate", "Duplicate"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
