# Generated by Django 6.0.5 on 2026-05-05 19:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brands", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("carousel", "Carousel"),
                            ("full_post", "Full post"),
                            ("image_prompt", "Image prompt"),
                            ("video_future", "Video future"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("feed_square", "Feed square"),
                            ("feed_portrait", "Feed portrait"),
                            ("story", "Story"),
                            ("reel_cover", "Reel cover"),
                            ("carousel", "Carousel"),
                        ],
                        default="feed_square",
                        max_length=30,
                    ),
                ),
                ("prompt_input", models.TextField()),
                ("generated_text", models.TextField(blank=True, default="")),
                ("generated_payload", models.JSONField(blank=True, default=dict)),
                ("generated_image_url", models.URLField(blank=True, default="")),
                ("ai_provider", models.CharField(blank=True, default="", max_length=50)),
                ("ai_model", models.CharField(blank=True, default="", max_length=100)),
                ("points_spent", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_requests",
                        to="brands.brand",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_requests",
                        to="brands.brandtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
