# Generated by Django 6.0.5 on 2026-05-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("trialing", "Trialing"),
                    ("past_due", "Past due"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                    ("incomplete", "Incomplete"),
                    ("unknown", "Unknown"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
