# Generated by Django 6.0.5 on 2026-05-05 19:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("niche", models.CharField(max_length=255)),
                ("target_audience", models.TextField(blank=True, default="")),
                ("tone_of_voice", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("products_services", models.TextField(blank=True, default="")),
                ("website", models.URLField(blank=True, default="")),
                ("instagram_handle", models.CharField(blank=True, default="", max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="brands/logos/")),
                ("primary_color", models.CharField(blank=True, default="", max_length=20)),
                ("secondary_color", models.CharField(blank=True, default="", max_length=20)),
                ("language", models.CharField(default="en", max_length=10)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="BrandTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_prompt", models.TextField()),
                ("visual_style", models.TextField(blank=True, default="")),
                ("copywriting_style", models.TextField(blank=True, default="")),
                ("forbidden_topics", models.TextField(blank=True, default="")),
                ("preferred_cta", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("brand", "name")},
            },
        ),
    ]
