# Generated by Django 6.0.5 on 2026-05-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="website_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
